name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Clone repo
      run: git clone https://github.com/cakshat/mslearn-mlops-challenges/ chal1.1
    - name: Create Compute Instance
      run: az ml compute create --name "ci-mlops" --size STANDARD_DS11_V2 --type ComputeInstance --resource-group rg-mlops-challenges --workspace-name ws-mlops-challenges
    - name: Trigger AML job created in challenge1
      run: az ml job create --file ./chal1.1/src/job.yml --resource-group rg-mlops-challenges --workspace-name ws-mlops-challenges


