name: GitHub Actions workflow-> triggered by changes being pushed to the main branch, with two jobs experiment and production

on: 
  pull_request:
jobs:
  experiment:
    name: Experiment Job
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Clone repo
        run: git clone https://github.com/cakshat/mslearn-mlops-challenges/ chal1.1
      - name: Create Compute Cluster
        run: az ml compute create --name "cc-mlops" --size STANDARD_DS11_V2 --type AmlCompute --resource-group rg-mlops-challenges --workspace-name ws-mlops-challenges
      - name: Trigger AML job created in challenge1
        run: az ml job create --file ./chal1.1/src/job.yml --resource-group rg-mlops-challenges --workspace-name ws-mlops-challenges
    
    
  production:
    name: Production Job
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Clone repo
        run: git clone https://github.com/cakshat/mslearn-mlops-challenges/ chal1.2
      - name: Create Compute Cluster
        run: az ml compute create --name "cc-mlops-second" --size STANDARD_DS11_V2 --type AmlCompute --resource-group rg-mlops-challenges --workspace-name ws-mlops-challenges-2
      - name: Trigger AML job created in challenge1
        run: az ml job create --file ./chal1.2/src/job.yml --resource-group rg-mlops-challenges --workspace-name ws-mlops-challenges-2
